<?php require_once 'header.phtml' ?>

<div class="card-body mx-5 p-2 rounded contentList">
    <div class="d-flex align-items-center mb-2">
        <h4 class="card-title"><?= $client['cliente']->nombre ?></h4>
        <p class="mb-0 ms-1">(<strong><?= $client['cliente']->telefono ?></strong>)</p>
    </div>
    <ul class="list-group">
        <?php foreach ($client['trabajos'] as $trabajo) : ?>
            <li class="list-group-item listStyle">
                <strong>Fecha:</strong> <?= $trabajo->fecha_trabajo ?><br>
                <strong>Trabajo Realizado:</strong> <?= $trabajo->trabajo_realizado ?><br>
                <strong>Descripción:</strong> <?= $trabajo->descripcion ?><br>
            </li>
        <?php endforeach ?>
    </ul>
</div>

<?php require_once 'footer.phtml' ?>